services:
  gateway:
    build: .
    image: panomete-api-gateway
    container_name: panomete-api-gateway
    restart: always
    ports:
      - "8000:8000"
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true