name: deploy-gateway
on:
  push:
    branches:
      - release

jobs:
    deploy:
      runs-on: [self-hosted]
      steps:
        - name: checkout code
        - uses: actions/checkout@v5.0.0

        - name: locate all file
        - run: la > output.txt

        - name: see dockerfile
        - run: cat Dockerfile > dockerfile.txt
